### ISSUE TITLE
client.CreateUser incorrect Fingerprint / IPAddress

### ISSUE THREAD

**Issue by evilfrog** [SynapseFI/SynapseGo#12]
https://github.com/SynapseFI/SynapseGo/blob/master/client.go#L284

According to the code and docs, you need to provide FINGERPRINT and then IP_ADDRESS

The user created though has different fingerprint.

If you create user with:

```
client.CreateUser(body, "FINGERPRINT", "IP_ADDRESS")
```
the actual fingerprint is `IP_ADDRESS` (go to uat-dashboard, and try logging in as the user with fingerprint 2fa)

**Comment by evilfrog** [comment]
OK, this is even stranger:

REPRO:
```
client := synapse.New(
		"client_id",
		"client_secret",
		"IP_ADDRESS_MAIN",
		"FINGERPRINT_MAIN",
		false,
		true,
	)
....
...
client.CreateUser(body, "FINGERPRINT_USER", "IP_ADDRESS_USER")
```
EXPECTED:
Fingerprint: `FINGERPRINT_USER`
IPAddress: `IP_ADDRESS_USER`

BUG:
Fingerprint: `IP_ADDRESS_MAIN`

Sooo.....it takes client init's IP_ADDRESS and uses it as user's fingerprint

**Comment by nathanpanics** [comment]
updated the sample, thanks for catching it: https://github.com/SynapseFI/SynapseGo/commit/60841467a8182c207995d973a91aecda7da22015#diff-6ff275754a0f6dec858e97654fe93ccb
