### ISSUE TITLE
IncorrectValues error handling

### ISSUE THREAD

**Issue by maeglindeveloper** [SynapseFI/SynapseGo#6]
Hi @nathanielniosco 

I'm trying to add documents to a user. If a value is not well formatted (lets say **Legal name**) in the **users.go** file, do method, it will be blocked inside the switch case **IncorrectValues** with the following error 

```
{
  "error": {
    "en": "Invalid field value supplied. Invalid name supplied. Please supply fullname."
  },
  "error_code": "400",
  "http_code": "409",
  "success": false
}
```
It loops trying to then **GetRefreshToken()**, **Authenticate()** until it reachs the API request limit rate. Maybe those kind of errors should be handled differently ?

Thanks in advance :)

**Comment by nathanpanics** [comment]
Thank you @maeglindeveloper! Looking into how to better handle this.
