### ISSUE TITLE
user.GetStatements stuck in authenticate loop

### ISSUE THREAD

**Issue by naveedroost** [SynapseFI/SynapseGo#9]
Successfully do `client.GetUser(...)` followed by `user.GetStatements("limit=1&per_page=1")`

The get statements call gets stuck in an authentication loop throwing invalid authentication credentials error then attempting to oauth the user with .Authenticate ... forever.

Please help!

**Comment by nathanpanics** [comment]
Hi @naveedroost,

The issue was brought up here: https://github.com/SynapseFI/SynapseGo/issues/4 and should be fixed.
Please update the SynapseGo package and re-run the calls.
